// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

export interface ResponseDataRefunds {
    authCode: Payabli.Authcode;
    expectedProcessingDateTime: (Payabli.ExpectedProcessingDateTime | undefined) | null;
    /** This field isn't applicable to refund operations. */
    avsResponseText?: Payabli.AvsResponseText;
    customerId: Payabli.CustomerId | null;
    /** This field isn't applicable to refund operations. */
    cvvResponseText: Payabli.CvvResponseText | null;
    /** This field isn't applicable to refund operations. */
    methodReferenceId: Payabli.MethodReferenceId | null;
    referenceId: Payabli.Referenceidtrans;
    resultCode: Payabli.ResultCode;
    /** Text description of the transaction result */
    resultText: string;
}
