// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

/**
 * A successful response returns a bill object with all its details. If the bill isn't found, the response will contain an error message.
 */
export interface GetBillResponse {
    responseCode?: Payabli.Responsecode | undefined;
    pageIdentifier?: Payabli.PageIdentifier | undefined;
    roomId?: Payabli.RoomIdNotInUse | undefined;
    isSuccess?: Payabli.IsSuccess | undefined;
    responseText: Payabli.ResponseText;
    responseData?: Payabli.BillResponseData | undefined;
}
