// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         vendorId: 42,
 *         expenseLimit: 500,
 *         maxNumberOfUses: 3,
 *         exactAmount: false,
 *         expenseLimitPeriod: "monthly",
 *         billingCycle: "monthly",
 *         billingCycleDay: "1",
 *         dailyTransactionCount: 5,
 *         dailyAmountLimit: 200,
 *         transactionAmountLimit: 100,
 *         mcc: "5411",
 *         tcc: "R",
 *         misc1: "PO-98765",
 *         misc2: "Dept-Finance"
 *     }
 */
export interface CreateGhostCardRequestBody {
    /** ID of the vendor who receives the card. The vendor must belong to the paypoint and have an active status. */
    vendorId: number;
    /** Spending limit for the card. Must be greater than `0` and can't exceed the paypoint's configured payout credit limit. */
    expenseLimit: number;
    /** Requested expiration date for the card. If not provided, defaults to 30 days from creation. */
    expirationDate?: string;
    /** Initial load amount for the card. Defaults to `0`. */
    amount?: number;
    /** Maximum number of times the card can be used. If `0` or negative, defaults to `9999`. Ignored and set to `1` when `exactAmount` is `true`. */
    maxNumberOfUses?: number;
    /** When `true`, restricts the card to a single use. `maxNumberOfUses` is automatically set to `1` regardless of any other value provided. */
    exactAmount?: boolean;
    /** Time period over which `expenseLimit` applies (for example, `monthly` or `weekly`). No server-side enforcement. */
    expenseLimitPeriod?: string;
    /** Billing cycle identifier. */
    billingCycle?: string;
    /** Day within the billing cycle. */
    billingCycleDay?: string;
    /** Maximum number of transactions allowed per day. Defaults to `0` (unlimited). */
    dailyTransactionCount?: number;
    /** Maximum total spend allowed per day. Defaults to `0` (unlimited). */
    dailyAmountLimit?: number;
    /** Maximum spend allowed per single transaction. Defaults to `0` (unlimited). */
    transactionAmountLimit?: number;
    /** Merchant Category Code to restrict where the card can be used. Must be a valid MCC if provided. */
    mcc?: string;
    /** Transaction Category Code to restrict where the card can be used. Must be a valid TCC if provided. */
    tcc?: string;
    /** Custom metadata field. Stored on the card record. */
    misc1?: string;
    /** Custom metadata field. Stored on the card record. */
    misc2?: string;
}
