/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ConfigureOrganizationRequest {
    cascade?: Payabli.Cascade;
    isEnabled?: Payabli.IsEnabled;
    orgId?: Payabli.OrganizationId;
}
