// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Payabli from "../../../index.js";

export declare namespace InvoiceClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class InvoiceClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<InvoiceClient.Options>;

    constructor(options: InvoiceClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Creates an invoice in an entrypoint.
     *
     * @param {string} entry - The paypoint's entrypoint identifier. [Learn more](/developers/api-reference/api-overview#entrypoint-vs-entry)
     * @param {Payabli.AddInvoiceRequest} request
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.addInvoice("8cfec329267", {
     *         body: {
     *             customerData: {
     *                 firstName: "Tamara",
     *                 lastName: "Bagratoni",
     *                 customerNumber: "3"
     *             },
     *             invoiceData: {
     *                 items: [{
     *                         itemProductName: "Adventure Consult",
     *                         itemDescription: "Consultation for Georgian tours",
     *                         itemCost: 100,
     *                         itemQty: 1,
     *                         itemMode: 1,
     *                         itemTotalAmount: 1
     *                     }, {
     *                         itemProductName: "Deposit ",
     *                         itemDescription: "Deposit for trip planning",
     *                         itemCost: 882.37,
     *                         itemQty: 1,
     *                         itemTotalAmount: 1
     *                     }],
     *                 invoiceDate: "2025-10-19",
     *                 invoiceType: 0,
     *                 invoiceStatus: 1,
     *                 frequency: "onetime",
     *                 invoiceAmount: 982.37,
     *                 discount: 10,
     *                 invoiceNumber: "INV-3"
     *             }
     *         }
     *     })
     */
    public addInvoice(
        entry: string,
        request: Payabli.AddInvoiceRequest,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.InvoiceResponseWithoutData> {
        return core.HttpResponsePromise.fromPromise(this.__addInvoice(entry, request, requestOptions));
    }

    private async __addInvoice(
        entry: string,
        request: Payabli.AddInvoiceRequest,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.InvoiceResponseWithoutData>> {
        const { forceCustomerCreation, idempotencyKey, body: _body } = request;
        const _queryParams: Record<string, unknown> = {
            forceCustomerCreation,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ idempotencyKey: idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/${core.url.encodePathParam(entry)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.InvoiceResponseWithoutData, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/Invoice/{entry}");
    }

    /**
     * Deletes an invoice that's attached to a file.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {string} filename - The filename in Payabli. Filename is `zipName` in response to a request to `/api/Invoice/{idInvoice}`. Here, the filename is `0_Bill.pdf``.
     *                            "DocumentsRef": {
     *                              "zipfile": "inva_269.zip",
     *                              "filelist": [
     *                                {
     *                                  "originalName": "Bill.pdf",
     *                                  "zipName": "0_Bill.pdf",
     *                                  "descriptor": null
     *                                }
     *                              ]
     *                            }
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.deleteAttachedFromInvoice(23548884, "0_Bill.pdf")
     */
    public deleteAttachedFromInvoice(
        idInvoice: number,
        filename: string,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.InvoiceResponseWithoutData> {
        return core.HttpResponsePromise.fromPromise(
            this.__deleteAttachedFromInvoice(idInvoice, filename, requestOptions),
        );
    }

    private async __deleteAttachedFromInvoice(
        idInvoice: number,
        filename: string,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.InvoiceResponseWithoutData>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/attachedFileFromInvoice/${core.url.encodePathParam(idInvoice)}/${core.url.encodePathParam(filename)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.InvoiceResponseWithoutData, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/Invoice/attachedFileFromInvoice/{idInvoice}/{filename}",
        );
    }

    /**
     * Deletes a single invoice from an entrypoint.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.deleteInvoice(23548884)
     */
    public deleteInvoice(
        idInvoice: number,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.InvoiceResponseWithoutData> {
        return core.HttpResponsePromise.fromPromise(this.__deleteInvoice(idInvoice, requestOptions));
    }

    private async __deleteInvoice(
        idInvoice: number,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.InvoiceResponseWithoutData>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/${core.url.encodePathParam(idInvoice)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.InvoiceResponseWithoutData, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/Invoice/{idInvoice}");
    }

    /**
     * Updates details for a single invoice in an entrypoint.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {Payabli.EditInvoiceRequest} request
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.editInvoice(332, {
     *         body: {
     *             invoiceData: {
     *                 items: [{
     *                         itemProductName: "Deposit",
     *                         itemDescription: "Deposit for trip planning",
     *                         itemCost: 882.37,
     *                         itemQty: 1
     *                     }],
     *                 invoiceDate: "2025-10-19",
     *                 invoiceAmount: 982.37,
     *                 invoiceNumber: "INV-6"
     *             }
     *         }
     *     })
     */
    public editInvoice(
        idInvoice: number,
        request: Payabli.EditInvoiceRequest,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.InvoiceResponseWithoutData> {
        return core.HttpResponsePromise.fromPromise(this.__editInvoice(idInvoice, request, requestOptions));
    }

    private async __editInvoice(
        idInvoice: number,
        request: Payabli.EditInvoiceRequest,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.InvoiceResponseWithoutData>> {
        const { forceCustomerCreation, body: _body } = request;
        const _queryParams: Record<string, unknown> = {
            forceCustomerCreation,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/${core.url.encodePathParam(idInvoice)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.InvoiceResponseWithoutData, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/Invoice/{idInvoice}");
    }

    /**
     * Retrieves a file attached to an invoice.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {string} filename - The filename in Payabli. Filename is `zipName` in the response to a request to `/api/Invoice/{idInvoice}`. Here, the filename is `0_Bill.pdf``.
     *                            ```
     *                              "DocumentsRef": {
     *                                "zipfile": "inva_269.zip",
     *                                "filelist": [
     *                                  {
     *                                    "originalName": "Bill.pdf",
     *                                    "zipName": "0_Bill.pdf",
     *                                    "descriptor": null
     *                                  }
     *                                ]
     *                              }
     *                              ```
     * @param {Payabli.GetAttachedFileFromInvoiceRequest} request
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.getAttachedFileFromInvoice(1, "filename")
     */
    public getAttachedFileFromInvoice(
        idInvoice: number,
        filename: string,
        request: Payabli.GetAttachedFileFromInvoiceRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.FileContent> {
        return core.HttpResponsePromise.fromPromise(
            this.__getAttachedFileFromInvoice(idInvoice, filename, request, requestOptions),
        );
    }

    private async __getAttachedFileFromInvoice(
        idInvoice: number,
        filename: string,
        request: Payabli.GetAttachedFileFromInvoiceRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.FileContent>> {
        const { returnObject } = request;
        const _queryParams: Record<string, unknown> = {
            returnObject,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/attachedFileFromInvoice/${core.url.encodePathParam(idInvoice)}/${core.url.encodePathParam(filename)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.FileContent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/Invoice/attachedFileFromInvoice/{idInvoice}/{filename}",
        );
    }

    /**
     * Retrieves a single invoice by ID.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.getInvoice(23548884)
     */
    public getInvoice(
        idInvoice: number,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.GetInvoiceRecord> {
        return core.HttpResponsePromise.fromPromise(this.__getInvoice(idInvoice, requestOptions));
    }

    private async __getInvoice(
        idInvoice: number,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.GetInvoiceRecord>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/${core.url.encodePathParam(idInvoice)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.GetInvoiceRecord, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/Invoice/{idInvoice}");
    }

    /**
     * Retrieves the next available invoice number for a paypoint.
     *
     * @param {string} entry - The paypoint's entrypoint identifier. [Learn more](/developers/api-reference/api-overview#entrypoint-vs-entry)
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.getInvoiceNumber("8cfec329267")
     */
    public getInvoiceNumber(
        entry: string,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.InvoiceNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getInvoiceNumber(entry, requestOptions));
    }

    private async __getInvoiceNumber(
        entry: string,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.InvoiceNumberResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/getNumber/${core.url.encodePathParam(entry)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.InvoiceNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/Invoice/getNumber/{entry}");
    }

    /**
     * Returns a list of invoices for an entrypoint. Use filters to limit results. Include the `exportFormat` query parameter to return the results as a file instead of a JSON response.
     *
     * @param {string} entry - The paypoint's entrypoint identifier. [Learn more](/developers/api-reference/api-overview#entrypoint-vs-entry)
     * @param {Payabli.ListInvoicesRequest} request
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.listInvoices("8cfec329267", {
     *         fromRecord: 251,
     *         limitRecord: 0,
     *         sortBy: "desc(field_name)"
     *     })
     */
    public listInvoices(
        entry: string,
        request: Payabli.ListInvoicesRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.QueryInvoiceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listInvoices(entry, request, requestOptions));
    }

    private async __listInvoices(
        entry: string,
        request: Payabli.ListInvoicesRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.QueryInvoiceResponse>> {
        const { exportFormat, fromRecord, limitRecord, parameters, sortBy } = request;
        const _queryParams: Record<string, unknown> = {
            exportFormat: exportFormat != null ? exportFormat : undefined,
            fromRecord,
            limitRecord,
            parameters: parameters != null ? toJson(parameters) : undefined,
            sortBy,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Query/invoices/${core.url.encodePathParam(entry)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.QueryInvoiceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/Query/invoices/{entry}");
    }

    /**
     * Returns a list of invoices for an org. Use filters to limit results. Include the `exportFormat` query parameter to return the results as a file instead of a JSON response.
     *
     * @param {number} orgId - The numeric identifier for organization, assigned by Payabli.
     * @param {Payabli.ListInvoicesOrgRequest} request
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.listInvoicesOrg(123, {
     *         fromRecord: 251,
     *         limitRecord: 0,
     *         sortBy: "desc(field_name)"
     *     })
     */
    public listInvoicesOrg(
        orgId: number,
        request: Payabli.ListInvoicesOrgRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.QueryInvoiceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listInvoicesOrg(orgId, request, requestOptions));
    }

    private async __listInvoicesOrg(
        orgId: number,
        request: Payabli.ListInvoicesOrgRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.QueryInvoiceResponse>> {
        const { exportFormat, fromRecord, limitRecord, parameters, sortBy } = request;
        const _queryParams: Record<string, unknown> = {
            exportFormat: exportFormat != null ? exportFormat : undefined,
            fromRecord,
            limitRecord,
            parameters: parameters != null ? toJson(parameters) : undefined,
            sortBy,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Query/invoices/org/${core.url.encodePathParam(orgId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.QueryInvoiceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/Query/invoices/org/{orgId}");
    }

    /**
     * Sends an invoice from an entrypoint via email.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {Payabli.SendInvoiceRequest} request
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.sendInvoice(23548884, {
     *         attachfile: true,
     *         mail2: "tamara@example.com"
     *     })
     */
    public sendInvoice(
        idInvoice: number,
        request: Payabli.SendInvoiceRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.SendInvoiceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__sendInvoice(idInvoice, request, requestOptions));
    }

    private async __sendInvoice(
        idInvoice: number,
        request: Payabli.SendInvoiceRequest = {},
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.SendInvoiceResponse>> {
        const { attachfile, mail2 } = request;
        const _queryParams: Record<string, unknown> = {
            attachfile,
            mail2,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Invoice/send/${core.url.encodePathParam(idInvoice)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.SendInvoiceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/Invoice/send/{idInvoice}");
    }

    /**
     * Export a single invoice in PDF format.
     *
     * @param {number} idInvoice - Invoice ID
     * @param {InvoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payabli.BadRequestError}
     * @throws {@link Payabli.UnauthorizedError}
     * @throws {@link Payabli.InternalServerError}
     * @throws {@link Payabli.ServiceUnavailableError}
     *
     * @example
     *     await client.invoice.getInvoicePdf(23548884)
     */
    public getInvoicePdf(
        idInvoice: number,
        requestOptions?: InvoiceClient.RequestOptions,
    ): core.HttpResponsePromise<Payabli.File_> {
        return core.HttpResponsePromise.fromPromise(this.__getInvoicePdf(idInvoice, requestOptions));
    }

    private async __getInvoicePdf(
        idInvoice: number,
        requestOptions?: InvoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payabli.File_>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PayabliEnvironment.Sandbox,
                `Export/invoicePdf/${core.url.encodePathParam(idInvoice)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payabli.File_, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payabli.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Payabli.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Payabli.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Payabli.ServiceUnavailableError(
                        _response.error.body as Payabli.PayabliApiResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayabliError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/Export/invoicePdf/{idInvoice}",
        );
    }
}
