// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

/**
 * Response body for queries about batches.
 *
 * @example
 *     {
 *         Summary: {
 *             pageSize: 20,
 *             totalAmount: 54049.71,
 *             totalNetAmount: 0,
 *             totalPages: 3,
 *             totalRecords: 3
 *         },
 *         Records: [{
 *                 IdBatch: 1049,
 *                 BatchNumber: "batch_2857_combined_08-26-2025_001",
 *                 TransferIdentifier: null,
 *                 EventsData: [{
 *                         description: "Created",
 *                         eventTime: "2025-08-25T03:19:27.6190027-04:00",
 *                         source: "api"
 *                     }],
 *                 ConnectorName: "GP",
 *                 BatchDate: "2025-08-25T20:00:00",
 *                 BatchAmount: 0,
 *                 BatchFeesAmount: 0,
 *                 BatchAuthAmount: 0,
 *                 BatchReleasedAmount: 0,
 *                 BatchHoldAmount: 0,
 *                 BatchReturnedAmount: 0,
 *                 BatchRefundAmount: 0,
 *                 BatchSplitAmount: 0,
 *                 BatchStatus: 2,
 *                 BatchRecords: 2,
 *                 PaypointId: 187,
 *                 PaypointName: "Gruzya Adventure Outfitters, LLC",
 *                 PaypointDba: "Gruzya Adventure Outfitters",
 *                 ParentOrgName: "Pilgrim Planner",
 *                 ParentOrgId: 105,
 *                 externalPaypointID: null,
 *                 EntryName: "47f4f8c7e1",
 *                 BankName: null,
 *                 BatchType: 0,
 *                 Method: "combined",
 *                 ExpectedDepositDate: "2025-08-26T00:00:00Z",
 *                 DepositDate: null,
 *                 TransferDate: "2025-08-26T00:00:00Z",
 *                 Transfer: null
 *             }, {
 *                 IdBatch: 1043,
 *                 BatchNumber: "BT-2023041817-187",
 *                 TransferIdentifier: null,
 *                 EventsData: null,
 *                 ConnectorName: null,
 *                 BatchDate: "2023-04-18T17:01:03Z",
 *                 BatchAmount: 219.02,
 *                 BatchFeesAmount: 0,
 *                 BatchAuthAmount: 0,
 *                 BatchReleasedAmount: 0,
 *                 BatchHoldAmount: 0,
 *                 BatchReturnedAmount: 0,
 *                 BatchRefundAmount: 0,
 *                 BatchSplitAmount: 0,
 *                 BatchStatus: 2,
 *                 BatchRecords: 1,
 *                 PaypointId: 187,
 *                 PaypointName: "Gruzya Adventure Outfitters, LLC",
 *                 PaypointDba: "Gruzya Adventure Outfitters",
 *                 ParentOrgName: "Pilgrim Planner",
 *                 ParentOrgId: 105,
 *                 externalPaypointID: null,
 *                 EntryName: "d193cf9a46",
 *                 BankName: null,
 *                 BatchType: 0,
 *                 Method: "card",
 *                 ExpectedDepositDate: "2023-04-19T00:00:00Z",
 *                 DepositDate: null,
 *                 TransferDate: "2025-09-02T00:00:00Z",
 *                 Transfer: null
 *             }, {
 *                 IdBatch: 1012,
 *                 BatchNumber: "BT-2023041421-187",
 *                 TransferIdentifier: "ec310c3d-d4bf-4670-9524-00fcc4ab6a2a",
 *                 EventsData: [{
 *                         description: "Created",
 *                         eventTime: "2023-04-14T21:01:03Z",
 *                         source: "api"
 *                     }, {
 *                         description: "Closed",
 *                         eventTime: "2023-04-15T03:05:10Z",
 *                         refData: "batchId: 1012",
 *                         source: "worker"
 *                     }],
 *                 ConnectorName: "GP",
 *                 BatchDate: "2023-04-14T21:01:03Z",
 *                 BatchAmount: 1080.44,
 *                 BatchFeesAmount: 0,
 *                 BatchAuthAmount: 1080.44,
 *                 BatchReleasedAmount: 0,
 *                 BatchHoldAmount: 0,
 *                 BatchReturnedAmount: 0,
 *                 BatchRefundAmount: 0,
 *                 BatchSplitAmount: 0,
 *                 BatchStatus: 2,
 *                 BatchRecords: 4,
 *                 PaypointId: 187,
 *                 PaypointName: "Gruzya Adventure Outfitters, LLC",
 *                 PaypointDba: "Gruzya Adventure Outfitters",
 *                 ParentOrgName: "Pilgrim Planner",
 *                 ParentOrgId: 105,
 *                 externalPaypointID: null,
 *                 EntryName: "d193cf9a46",
 *                 BankName: null,
 *                 BatchType: 0,
 *                 Method: "card",
 *                 ExpectedDepositDate: "2023-04-15T00:00:00Z",
 *                 DepositDate: null,
 *                 TransferDate: "2025-09-02T00:00:00Z",
 *                 Transfer: {
 *                     TransferId: 5998,
 *                     TransferDate: "2025-09-02T00:00:00Z",
 *                     Processor: "gp",
 *                     TransferStatus: 1,
 *                     GrossAmount: 1080.44,
 *                     ChargeBackAmount: 0,
 *                     ReturnedAmount: 0,
 *                     RefundAmount: 0,
 *                     HoldAmount: 0,
 *                     ReleasedAmount: 0,
 *                     BillingFeesAmount: 0,
 *                     ThirdPartyPaidAmount: 0,
 *                     AdjustmentsAmount: 0,
 *                     NetFundedAmount: 1080.44
 *                 }
 *             }]
 *     }
 */
export interface QueryBatchesResponse {
    Records: QueryBatchesResponse.Records.Item[];
    Summary: Payabli.BatchSummary;
}

export namespace QueryBatchesResponse {
    export type Records = Records.Item[];

    export namespace Records {
        export interface Item {
            /** The batch ID. */
            IdBatch: number | null;
            BatchNumber: Payabli.BatchNumber | null;
            TransferIdentifier: Payabli.TransferIdentifier | null;
            /** Events associated with the batch. */
            EventsData: Payabli.GeneralEvents[] | null;
            /** */
            ConnectorName: string | null;
            /** The batch date. */
            BatchDate: string | null;
            /** The amount of the batch. */
            BatchAmount: number | null;
            /** The total of fees in the batch. */
            BatchFeesAmount: number | null;
            /** */
            BatchAuthAmount: number | null;
            /** Previously held funds that have been released after a risk review. */
            BatchReleasedAmount: number | null;
            /** The total amount of the batch that's being held for fraud or risk concerns. */
            BatchHoldAmount: number | null;
            /** Total amount of ACH returns deducted from batch. */
            BatchReturnedAmount: number | null;
            /** The total amount of refunds deducted from batch. */
            BatchRefundAmount: number | null;
            /** Total of split transactions that included split funding instructions at the time of authorization. */
            BatchSplitAmount: number | null;
            /** The batch status. See [Batch Status](/developers/references/money-in-statuses#batch-status) for more. */
            BatchStatus: number;
            /** The number of records in the batch. */
            BatchRecords: number;
            PaypointId: Payabli.PaypointId | null;
            PaypointName: Payabli.PaypointName | null;
            PaypointDba: Payabli.Dbaname | null;
            /** The entrypoint's parent org. */
            ParentOrgName: Payabli.OrgParentName;
            /** The parent organization ID. */
            ParentOrgId: number;
            externalPaypointID: Payabli.ExternalPaypointId | null;
            EntryName: Payabli.Entrypointfield;
            /** The bank name. */
            BankName: string | null;
            /** The batch type. */
            BatchType: number | null;
            /** The payment method used. */
            Method: string | null;
            ExpectedDepositDate: Payabli.ExpectedDepositDate | null;
            DepositDate: Payabli.DepositDate | null;
            /** The batch transfer date. */
            TransferDate: string | null;
            /** Transfer details for the batch. */
            Transfer: Payabli.QueryBatchesTransfer | null;
        }
    }
}
