/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../../index";

/**
 * @example
 *     {
 *         idempotencyKey: "6B29FC40-CA47-1067-B31D-00DD010662DA",
 *         paymentMethod: {
 *             cardnumber: "4111111111111111",
 *             method: "card"
 *         }
 *     }
 */
export interface RequestPaymentValidate {
    idempotencyKey?: Payabli.IdempotencyKey | undefined;
    accountId?: Payabli.Accountid | undefined;
    entryPoint?: Payabli.Entrypointfield;
    orderDescription?: Payabli.Orderdescription | undefined;
    orderId?: Payabli.Orderid | undefined;
    /** Object describing payment method to use for transaction. */
    paymentMethod: Payabli.RequestPaymentValidatePaymentMethod;
}
