// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "8A29FC40-CA47-1067-B31D-00DD010662DB",
 *         source: "api",
 *         orderDescription: "Materials deposit",
 *         amount: 100,
 *         refundDetails: {
 *             splitRefunding: [{
 *                     originationEntryPoint: "7f1a381696",
 *                     accountId: "187-342",
 *                     description: "Refunding undelivered materials",
 *                     amount: 60
 *                 }, {
 *                     originationEntryPoint: "7f1a381696",
 *                     accountId: "187-343",
 *                     description: "Refunding deposit for undelivered materials",
 *                     amount: 40
 *                 }]
 *         }
 *     }
 *
 * @example
 *     {
 *         idempotencyKey: "8A29FC40-CA47-1067-B31D-00DD010662DB",
 *         source: "api",
 *         orderDescription: "Materials deposit",
 *         amount: 70,
 *         refundDetails: {
 *             splitRefunding: [{
 *                     originationEntryPoint: "7f1a381696",
 *                     accountId: "187-342",
 *                     description: "Refunding undelivered materials",
 *                     amount: 40
 *                 }, {
 *                     originationEntryPoint: "7f1a381696",
 *                     accountId: "187-343",
 *                     description: "Refunding deposit for undelivered materials",
 *                     amount: 30
 *                 }]
 *         }
 *     }
 */
export interface RequestRefund {
    idempotencyKey?: Payabli.IdempotencyKey;
    /**
     * Amount to refund from original transaction, minus any service fees charged on the original transaction.
     *
     * The amount provided can't be greater than the original total amount of the transaction, minus service fees. For example, if a transaction was $90 plus a $10 service fee, you can refund up to $90.
     *
     * An amount equal to zero will refund the total amount authorized minus any service fee.
     */
    amount?: number;
    ipaddress?: Payabli.IpAddress;
    orderDescription?: Payabli.Orderdescription;
    orderId?: Payabli.OrderId;
    refundDetails?: Payabli.RefundDetail;
    source?: Payabli.Source;
}
