/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "6B29FC40-CA47-1067-B31D-00DD010662DA",
 *         customerData: {
 *             billingAddress1: "5127 Linkwood ave",
 *             customerNumber: "100"
 *         },
 *         entrypoint: "my-entrypoint",
 *         paymentDetails: {
 *             serviceFee: 0,
 *             totalAmount: 1
 *         },
 *         paymentMethod: {
 *             achAccount: "88354454",
 *             achAccountType: "Checking",
 *             achHolder: "John Smith",
 *             achRouting: "021000021",
 *             method: "ach"
 *         }
 *     }
 *
 * @example
 *     {
 *         idempotencyKey: "6B29FC40-CA47-1067-B31D-00DD010662DA",
 *         customerData: {
 *             billingAddress1: "125 Main Street",
 *             billingCity: "Kingsport",
 *             billingEmail: "johnnyp@email.com",
 *             company: "Acme, Inc",
 *             customerNumber: "100",
 *             firstName: "Johnny",
 *             lastName: "Poulsbo"
 *         },
 *         entrypoint: "my-entrypoint",
 *         paymentDetails: {
 *             serviceFee: 0,
 *             totalAmount: 1
 *         },
 *         paymentMethod: {
 *             achAccount: "88354554",
 *             achAccountType: "Checking",
 *             achHolder: "John Poulsbo",
 *             achRouting: "029000021",
 *             method: "ach"
 *         }
 *     }
 */
export interface RequestCredit {
    forceCustomerCreation?: Payabli.ForceCustomerCreation | undefined;
    idempotencyKey?: Payabli.IdempotencyKey;
    accountId?: Payabli.Accountid;
    /** Object describing the customer/payor. */
    customerData: Payabli.PayorDataRequest;
    entrypoint?: Payabli.Entrypointfield;
    orderDescription?: Payabli.Orderdescription;
    orderId?: Payabli.OrderId;
    paymentDetails: Payabli.PaymentDetailCredit;
    /** Object describing the ACH payment method to use for transaction. */
    paymentMethod: RequestCredit.PaymentMethod;
    source?: Payabli.Source;
    subdomain?: Payabli.Subdomain;
}

export namespace RequestCredit {
    /**
     * Object describing the ACH payment method to use for transaction.
     */
    export interface PaymentMethod {
        achAccount?: Payabli.Achaccount;
        achAccountType?: Payabli.Achaccounttype;
        achCode?: Payabli.AchSecCode;
        /** Bank account holder. */
        achHolder?: Payabli.AchHolder;
        achRouting?: Payabli.Achrouting;
        /** Method to use for the transaction. Must be ACH. */
        method: "ach";
    }
}
