/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExportBillsOrgRequestFormat = "csv" | "xlsx";
export const ExportBillsOrgRequestFormat = {
    Csv: "csv",
    Xlsx: "xlsx",
} as const;
