/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Payabli from "../index";
import * as core from "../../core";

export class ServiceUnavailableError extends errors.PayabliError {
    constructor(body: Payabli.PayabliApiResponse, rawResponse?: core.RawResponse) {
        super({
            message: "ServiceUnavailableError",
            statusCode: 503,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, ServiceUnavailableError.prototype);
    }
}
