// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

export interface ChargeBackResponse {
    /** Object with attached files to response */
    attachments?: Payabli.BoardingApplicationAttachments | undefined;
    /** Email of response submitter. */
    contactEmail?: Payabli.Email | undefined;
    /** Name of response submitter */
    contactName?: string | undefined;
    /** Timestamp when response was submitted, in UTC. */
    createdAt?: Payabli.CreatedAt | undefined;
    /** Chargeback response identifier */
    id?: number | undefined;
    /** Response notes */
    notes?: string | undefined;
}
