/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface MfaValidationData {
    mfaCode?: string;
    mfaValidationCode?: Payabli.MfaValidationCode;
}
