// This file was auto-generated by Fern from our API Definition.

import * as Payabli from "../index.js";

export interface AchAbsorbSection {
    multiTier?: boolean | undefined;
    tiers?: Payabli.AchTypesTiers[] | undefined;
    visible?: Payabli.Visible | undefined;
}
