// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface AuthCapturePayoutResponseData {
    authCode: Payabli.Authcode | null;
    referenceId: Payabli.Referenceidtrans;
    resultCode: Payabli.ResultCode;
    resultText: Payabli.Resulttext;
    avsResponseText: Payabli.AvsResponseText | null;
    cvvResponseText: Payabli.CvvResponseText | null;
    /** Payabli-generated unique ID of the vendor on the payout. Returns the same value as `vendorId`, or `0` when no vendor is associated. */
    customerId: Payabli.Vendoridtrans;
    /** Payabli-generated unique ID of the vendor on the payout. Returns the same value as `customerId`, or `0` when no vendor is associated. */
    vendorId: Payabli.Vendoridtrans;
    methodReferenceId: Payabli.MethodReferenceId | null;
}
