// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface AutoElement {
    enabled?: Payabli.Enabled;
    /** Type of end date */
    finish?: Payabli.Finishtype;
    /** accepted frequencies for autopay */
    frequency?: Payabli.FrequencyList;
    /** Value of pre-selected frequency */
    frequencySelected?: string;
    /** Header text for section */
    header?: string;
    order?: Payabli.Order;
    /** Range of days enabled in calendar. Leave empty to enable all days. */
    startDate?: string;
}
