/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

/**
 * Details about a bank account.
 */
export interface BankSection {
    visible?: Payabli.Visible | undefined;
    accountNumber?: Payabli.TemplateElement;
    accountType?: Payabli.TemplateElement;
    bankName?: Payabli.TemplateElement;
    routingNumber?: Payabli.TemplateElement;
}
