// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Details about a bank account.
 */
export interface BankSection {
    visible?: Payabli.Visible | undefined;
    accountNumber?: Payabli.TemplateElement | undefined;
    accountType?: Payabli.TemplateElement | undefined;
    bankName?: Payabli.TemplateElement | undefined;
    routingNumber?: Payabli.TemplateElement | undefined;
}
