// This file was auto-generated by Fern from our API Definition.

/**
 * Payment terms for invoice. If no terms are defined, then response data for
 * this field defaults to `NET30`. Mirrors the values in
 * [`Terms`](#schema-terms).
 */
export const BillDataPaymentTerms = {
    Pia: "PIA",
    Cia: "CIA",
    Ur: "UR",
    Net10: "NET10",
    Net20: "NET20",
    Net30: "NET30",
    Net45: "NET45",
    Net60: "NET60",
    Net90: "NET90",
    Eom: "EOM",
    Mfi: "MFI",
    FiveMfi: "5MFI",
    TenMfi: "10MFI",
    FifteenMfi: "15MFI",
    TwentyMfi: "20MFI",
    Two10Net30: "2/10NET30",
    Uf: "UF",
    TenUf: "10UF",
    TwentyUf: "20UF",
    TwentyFiveUf: "25UF",
    FiftyUf: "50UF",
} as const;
export type BillDataPaymentTerms = (typeof BillDataPaymentTerms)[keyof typeof BillDataPaymentTerms];
