/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

/**
 * Array of `LineItems` contained in bill.
 */
export type Billitems = Payabli.BillItem[] | undefined;
