// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface BillData {
    AdditionalData?: Payabli.AdditionalDataMap | undefined;
    attachments?: Payabli.Attachments | undefined;
    /** Company name of the recipient of the invoice. */
    company?: string | undefined;
    discount?: Payabli.Discount | undefined;
    dutyAmount?: Payabli.DutyAmount | undefined;
    /** First name of the recipient of the invoice. */
    firstName?: string | undefined;
    freightAmount?: Payabli.FreightAmount | undefined;
    /** Frequency of scheduled invoice. */
    frequency?: Payabli.Frequency | undefined;
    invoiceAmount?: Payabli.InvoiceAmount | undefined;
    /** Invoice date in any of the accepted formats: YYYY-MM-DD, MM/DD/YYYY. */
    invoiceDate?: string | undefined;
    /** Invoice due date in one of the accepted formats: YYYY-MM-DD, MM/DD/YYYY. */
    invoiceDueDate?: string | undefined;
    /** Indicate the date to finish a scheduled invoice cycle (`invoiceType`` = 1) in any of the accepted formats: YYYY-MM-DD, MM/DD/YYYY. */
    invoiceEndDate?: string | undefined;
    /** Invoice number. Identifies the invoice under a paypoint. */
    invoiceNumber?: Payabli.InvoiceNumber | undefined;
    invoiceStatus?: Payabli.Invoicestatus | undefined;
    invoiceType?: Payabli.InvoiceType | undefined;
    /** Array of line items included in the invoice. */
    items?: Payabli.BillItem[] | undefined;
    /** Last name of the recipient of the invoice. */
    lastName?: string | undefined;
    /** Notes included in the invoice. */
    notes?: string | undefined;
    paymentTerms?: Payabli.BillDataPaymentTerms | undefined;
    purchaseOrder?: Payabli.PurchaseOrder | undefined;
    shippingAddress1?: Payabli.Shippingaddress | undefined;
    shippingAddress2?: Payabli.Shippingaddressadditional | undefined;
    shippingCity?: Payabli.Shippingcity | undefined;
    shippingCountry?: Payabli.Shippingcountry | undefined;
    /** Shipping recipient's contact email address. */
    shippingEmail?: Payabli.Email | undefined;
    shippingFromZip?: Payabli.ShippingFromZip | undefined;
    /** Recipient phone number. */
    shippingPhone?: string | undefined;
    shippingState?: Payabli.Shippingstate | undefined;
    shippingZip?: Payabli.Shippingzip | undefined;
    summaryCommodityCode?: Payabli.SummaryCommodityCode | undefined;
    tax?: Payabli.Tax | undefined;
    termsConditions?: Payabli.TermsConditions | undefined;
}
