// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Approvals associated with the bill.
 */
export type BillApprovals = (Payabli.BillQueryRecord2BillApprovalsItem | undefined)[] | undefined;
