// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface BoardingLinkQueryRecord {
    acceptOauth?: Payabli.AcceptOauth | undefined;
    acceptRegister?: Payabli.AcceptRegister | undefined;
    builderData?: Payabli.BuilderData | undefined;
    entryAttributes?: Payabli.EntryAttributes | undefined;
    id?: number | undefined;
    /** Object containing logo file. */
    logo?: Payabli.FileContent | undefined;
    orgId?: Payabli.Orgid | undefined;
    "pageIdentifier:"?: Payabli.PageIdentifier | undefined;
    recipientEmailNotification?: Payabli.RecipientEmailNotification | undefined;
    referenceName?: Payabli.ReferenceName | undefined;
    referenceTemplateId?: Payabli.ReferenceTemplateId | undefined;
    resumable?: Payabli.Resumable | undefined;
}
