// This file was auto-generated by Fern from our API Definition.

/** Specify the size of the custom payment button. */
export const ButtonElementSize = {
    Sm: "sm",
    Md: "md",
    Lg: "lg",
} as const;
export type ButtonElementSize = (typeof ButtonElementSize)[keyof typeof ButtonElementSize];
