// This file was auto-generated by Fern from our API Definition.

/**
 * A field used internally by Payabli to categorize the transaction details. Values are:
 *   - `auth`: Any payment
 *   - `refund`: ACH return or Refund
 *   - `adj`: Adjustments
 *   - `cb`: Chargeback
 *   - `split`: Split amount
 */
export type Category = string;
