// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface CList {
    contactEmail?: Payabli.LinkData;
    contactName?: Payabli.LinkData;
    contactPhone?: Payabli.LinkData;
    contactTitle?: Payabli.LinkData;
}
