/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface ConfigureGooglePaypointApiResponse {
    isSuccess: Payabli.IsSuccess;
    pageIdentifier?: Payabli.PageIdentifier;
    responseCode?: Payabli.Responsecode;
    responseData: Payabli.GooglePayPaypointRegistrationData;
    responseText?: Payabli.ResponseText;
    /** Field not in use on this endpoint */
    roomId?: number;
}
