// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Response returned when creating a boarding application linked to an existing paypoint.
 */
export interface CreateApplicationFromPaypointResponse {
    responseCode?: Payabli.Responsecode | undefined;
    pageIdentifier?: Payabli.PageIdentifier | undefined;
    roomId?: Payabli.RoomIdNotInUse | undefined;
    isSuccess?: Payabli.IsSuccess | undefined;
    responseText: Payabli.ResponseText;
    responseData?: Payabli.CreateApplicationFromPaypointResponseData | undefined;
}
