/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface Element {
    enabled?: Payabli.Enabled;
    order?: Payabli.Order | undefined;
}
