// This file was auto-generated by Fern from our API Definition.

/**
 * The entity's entrypoint identifier. [Learn more](/developers/api-reference/api-overview#entrypoint-vs-entry)
 */
export type Entry = string;
