// This file was auto-generated by Fern from our API Definition.

/**
 * Origination channel, serialized as an integer: `0` None, `1` Ivr,
 * `2` Vault, `3` Ttp.
 */
export type EventSourceValue = number;
