// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * A fee schedule attached to a billable event. Flat and interchange-plus
 * schedules share this shape; `feeType` is the discriminator.
 */
export interface FeeSchedule {
    /** Fee schedule identifier. */
    id: number;
    /** The flat-fee component of the fee, for example `0.30`. */
    value: number;
    /** The percentage-rate component of the fee, for example `2.9`. */
    rate: number;
    passthrough: Payabli.PassthroughValue;
    /** Entity responsible for paying this fee. `null` when not set. */
    payor: Payabli.BillingEntity | null;
    /** Entity that collects this fee. `null` when not set. */
    collector: Payabli.BillingEntity | null;
    /**
     * Fallback payor used when the primary payor can't cover the fee. `null`
     * when not set.
     */
    overflowPayor: Payabli.BillingEntity | null;
    /** Collection cadence for the overflow payor. `null` when not set. */
    overflowCollectionSchedule: Payabli.CollectionScheduleValue | null;
    /** Floor on the combined fee (rate + flat value) for this schedule. */
    minimumTotal: number | null;
    /** Ceiling on the combined fee (rate + flat value) for this schedule. */
    maximumTotal: number | null;
    /**
     * When this schedule starts applying. Drives ordering when an event has
     * multiple schedules.
     */
    effectiveDate: string;
    /** When this schedule stops applying. `null` means no end date. */
    expirationDate: string | null;
    /** When this schedule was created. */
    createdAt: string;
    /** When this schedule was last updated. */
    updatedAt: string;
    /**
     * Identifier of the schedule's creator. Surfaces in the Payabli Portal as
     * "Configuration Owner" — informational, not a permission boundary.
     */
    createdBy: string;
    collectionSchedule: Payabli.CollectionScheduleValue;
    /** Day of the month a monthly bill is applied, when set. `null` otherwise. */
    billDate: number | null;
    /** Identifier of another fee schedule this one overrides. `null` otherwise. */
    overrideFeeScheduleId: number | null;
    feeType: Payabli.FeeTypeValue;
}
