// This file was auto-generated by Fern from our API Definition.

import * as Payabli from "../index.js";

export interface GeneralEvents {
    /** Event description. */
    description?: string | undefined;
    /** Event timestamp, in UTC. */
    eventTime?: string | undefined;
    /** Extra data. */
    extraData?: (string | null) | undefined;
    /** Reference data. */
    refData?: string | undefined;
    /** The event source. */
    source?: Payabli.Source | undefined;
}
