/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

/**
 * Settings for wallet payment methods.
 */
export interface MethodElementSettings {
    applePay?: Payabli.MethodElementSettingsApplePay;
}
