/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

export interface MethodElement {
    /** Flag indicating if all allowed payment methods will be pre-selected. */
    allMethodsChecked?: boolean;
    enabled?: Payabli.Enabled;
    /** Header text for section */
    header?: string;
    methods?: Payabli.MethodsList;
    order?: Payabli.Order;
    /** Settings for wallet payment methods. */
    settings?: MethodElement.Settings;
}

export namespace MethodElement {
    /**
     * Settings for wallet payment methods.
     */
    export interface Settings {
        applePay?: Settings.ApplePay;
    }

    export namespace Settings {
        export interface ApplePay {
            /** The Apple Pay button style. See [Apple Pay Button Style](/developers/developer-guides/hosted-payment-page-apple-pay#param-applepay-button-style) for more information. */
            buttonStyle?: ApplePay.ButtonStyle;
            /** The text on Apple Pay button. See [Apple Pay Button Type](/developers/developer-guides/hosted-payment-page-apple-pay#param-applepay-button-type) for more information. */
            buttonType?: ApplePay.ButtonType;
            /** The Apple Pay button locale. See [Apple Pay Button Language](/developers/developer-guides/hosted-payment-page-apple-pay#param-applepay-language) for more information. */
            language?: ApplePay.Language;
        }

        export namespace ApplePay {
            /**
             * The Apple Pay button style. See [Apple Pay Button Style](/developers/developer-guides/hosted-payment-page-apple-pay#param-applepay-button-style) for more information.
             */
            export type ButtonStyle = "black" | "white-outline" | "white";
            export const ButtonStyle = {
                Black: "black",
                WhiteOutline: "white-outline",
                White: "white",
            } as const;
            /**
             * The text on Apple Pay button. See [Apple Pay Button Type](/developers/developer-guides/hosted-payment-page-apple-pay#param-applepay-button-type) for more information.
             */
            export type ButtonType =
                | "plain"
                | "buy"
                | "donate"
                | "check-out"
                | "book"
                | "continue"
                | "top-up"
                | "order"
                | "rent"
                | "support"
                | "contribute"
                | "tip"
                | "pay";
            export const ButtonType = {
                Plain: "plain",
                Buy: "buy",
                Donate: "donate",
                CheckOut: "check-out",
                Book: "book",
                Continue: "continue",
                TopUp: "top-up",
                Order: "order",
                Rent: "rent",
                Support: "support",
                Contribute: "contribute",
                Tip: "tip",
                Pay: "pay",
            } as const;
            /**
             * The Apple Pay button locale. See [Apple Pay Button Language](/developers/developer-guides/hosted-payment-page-apple-pay#param-applepay-language) for more information.
             */
            export type Language =
                | "en-US"
                | "ar-AB"
                | "ca-ES"
                | "zh-CN"
                | "zh-HK"
                | "zh-TW"
                | "hr-HR"
                | "cs-CZ"
                | "da-DK"
                | "de-DE"
                | "nl-NL"
                | "en-AU"
                | "en-GB"
                | "fi-FI"
                | "fr-CA"
                | "fr-FR"
                | "el-GR"
                | "he-IL"
                | "hi-IN"
                | "hu-HU"
                | "id-ID"
                | "it-IT"
                | "ja-JP"
                | "ko-KR"
                | "ms-MY"
                | "nb-NO"
                | "pl-PL"
                | "pt-BR"
                | "pt-PT"
                | "ro-RO"
                | "ru-RU"
                | "sk-SK"
                | "es-MX"
                | "es-ES"
                | "sv-SE"
                | "th-TH"
                | "tr-TR"
                | "uk-UA"
                | "vi-VN";
            export const Language = {
                EnUs: "en-US",
                ArAb: "ar-AB",
                CaEs: "ca-ES",
                ZhCn: "zh-CN",
                ZhHk: "zh-HK",
                ZhTw: "zh-TW",
                HrHr: "hr-HR",
                CsCz: "cs-CZ",
                DaDk: "da-DK",
                DeDe: "de-DE",
                NlNl: "nl-NL",
                EnAu: "en-AU",
                EnGb: "en-GB",
                FiFi: "fi-FI",
                FrCa: "fr-CA",
                FrFr: "fr-FR",
                ElGr: "el-GR",
                HeIl: "he-IL",
                HiIn: "hi-IN",
                HuHu: "hu-HU",
                IdId: "id-ID",
                ItIt: "it-IT",
                JaJp: "ja-JP",
                KoKr: "ko-KR",
                MsMy: "ms-MY",
                NbNo: "nb-NO",
                PlPl: "pl-PL",
                PtBr: "pt-BR",
                PtPt: "pt-PT",
                RoRo: "ro-RO",
                RuRu: "ru-RU",
                SkSk: "sk-SK",
                EsMx: "es-MX",
                EsEs: "es-ES",
                SvSe: "sv-SE",
                ThTh: "th-TH",
                TrTr: "tr-TR",
                UkUa: "uk-UA",
                ViVn: "vi-VN",
            } as const;
        }
    }
}
