// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Settings for wallet payment methods.
 */
export interface MethodElementSettings {
    applePay?: Payabli.MethodElementSettingsApplePay | undefined;
}
