// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface NotificationQueryRecord {
    /** Notification content. */
    content?: Payabli.NotificationContent | undefined;
    /** Timestamp of when notification was created. */
    createdAt?: Payabli.CreatedAt | undefined;
    frequency?: Payabli.Frequencynotification | undefined;
    /** Timestamp of when notification was last updated. */
    lastUpdated?: Payabli.LastModified | undefined;
    method?: Payabli.Methodnotification | undefined;
    notificationId?: Payabli.NotificationId | undefined;
    ownerId?: Payabli.Ownerid | undefined;
    /** Name of entity owner of notification. */
    ownerName?: string | undefined;
    ownerType?: Payabli.Ownertype | undefined;
    /** Custom descriptor of source of notification. */
    source?: Payabli.Source | undefined;
    status?: Payabli.Statusnotification | undefined;
    target?: Payabli.Target | undefined;
}
