// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface NotificationContent {
    /** The notification's event name. */
    eventType?: NotificationContent.EventType;
    /**
     * Indicate the format of report file to be generated by the engine.
     * Used for `method` = *report-email* and *report-web*.
     */
    fileFormat?: NotificationContent.FileFormat;
    /** Array of pairs key:value to insert in request body to target in **method** = *web* or *report-web*. */
    internalData?: Payabli.KeyValueDuo[];
    /** The kind report to generate. For [automated reports](/developers/developer-guides/notifications-and-webhooks-overview#automated-reports) only. */
    reportName?: NotificationContent.ReportName;
    timeZone?: Payabli.Timezone;
    /** Used internally to reference the entity or object generating the event. */
    transactionId?: string;
    /** Array of pairs key:value to insert in header of request to target in **method** = *web* or *report-web*. */
    webHeaderParameters?: Payabli.KeyValueDuo[];
}

export namespace NotificationContent {
    /** The notification's event name. */
    export const EventType = {
        ApprovedPayment: "ApprovedPayment",
        AuthorizedPayment: "AuthorizedPayment",
        DeclinedPayment: "DeclinedPayment",
        OriginatedPayment: "OriginatedPayment",
        SettledPayment: "SettledPayment",
        SubscriptionCreated: "SubscriptionCreated",
        SubscriptionUpdated: "SubscriptionUpdated",
        SubscriptionCanceled: "SubscriptionCanceled",
        SubscriptionCompleted: "SubscriptionCompleted",
        FundedPayment: "FundedPayment",
        VoidedPayment: "VoidedPayment",
        RefundedPayment: "RefundedPayment",
        HoldTransaction: "HoldTransaction",
        ReleasedTransaction: "ReleasedTransaction",
        HoldBatch: "HoldBatch",
        ReleasedBatch: "ReleasedBatch",
        TransferDisabledCreditFund: "TransferDisabledCreditFund",
        TransferDisabledDebitFund: "TransferDisabledDebitFund",
        TransferNotAvailableBalance: "TransferNotAvailableBalance",
        TransferReturn: "TransferReturn",
        TransferSuccess: "TransferSuccess",
        TransferSuspended: "TransferSuspended",
        TransferError: "TransferError",
        SendReceipt: "SendReceipt",
        RecoveredTransaction: "RecoveredTransaction",
        CreatedApplication: "CreatedApplication",
        ApprovedApplication: "ApprovedApplication",
        FailedBoardingApplication: "FailedBoardingApplication",
        SubmittedApplication: "SubmittedApplication",
        ActivatedMerchant: "ActivatedMerchant",
        ReceivedChargeBack: "ReceivedChargeBack",
        ChargebackUpdated: "ChargebackUpdated",
        ReceivedRetrieval: "ReceivedRetrieval",
        RetrievalUpdated: "RetrievalUpdated",
        ReceivedAchReturn: "ReceivedAchReturn",
        HoldingApplication: "HoldingApplication",
        DeclinedApplication: "DeclinedApplication",
        BoardingApplication: "BoardingApplication",
        FraudAlert: "FraudAlert",
        InvoiceSent: "InvoiceSent",
        InvoicePaid: "InvoicePaid",
        InvoiceCreated: "InvoiceCreated",
        BillPaid: "BillPaid",
        BillApproved: "BillApproved",
        BillDisApproved: "BillDisApproved",
        BillCanceled: "BillCanceled",
        BillProcessing: "BillProcessing",
        CardCreated: "CardCreated",
        CardActivated: "CardActivated",
        CardDeactivated: "CardDeactivated",
        CardExpired: "CardExpired",
        CardExpiring: "CardExpiring",
        CardLimitUpdated: "CardLimitUpdated",
        BatchClosed: "BatchClosed",
        BatchNotClosed: "BatchNotClosed",
        PayOutFunded: "PayOutFunded",
        PayOutProcessed: "PayOutProcessed",
        PayOutCanceled: "PayOutCanceled",
        PayOutPaid: "PayOutPaid",
        PayOutReturned: "PayOutReturned",
        PayoutSubscriptionCreated: "PayoutSubscriptionCreated",
        PayoutSubscriptionUpdated: "PayoutSubscriptionUpdated",
        PayoutSubscriptionCanceled: "PayoutSubscriptionCanceled",
        PayoutSubscriptionCompleted: "PayoutSubscriptionCompleted",
        PayoutSubscriptionReminder: "PayoutSubscriptionReminder",
        ImportFileReceived: "importFileReceived",
        ImportFileProcessed: "importFileProcessed",
        ImportFileError: "importFileError",
        ExportFileSent: "exportFileSent",
        ExportFileError: "exportFileError",
        FailedEmailNotification: "FailedEmailNotification",
        FailedWebNotification: "FailedWebNotification",
        FailedSmsNotification: "FailedSMSNotification",
        UserPasswordExpiring: "UserPasswordExpiring",
        UserPasswordExpired: "UserPasswordExpired",
        TransactionNotFound: "TransactionNotFound",
        SystemAlert: "SystemAlert",
        Report: "Report",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
    /**
     * Indicate the format of report file to be generated by the engine.
     * Used for `method` = *report-email* and *report-web*.
     */
    export const FileFormat = {
        Json: "json",
        Csv: "csv",
        Xlsx: "xlsx",
    } as const;
    export type FileFormat = (typeof FileFormat)[keyof typeof FileFormat];
    /** The kind report to generate. For [automated reports](/developers/developer-guides/notifications-and-webhooks-overview#automated-reports) only. */
    export const ReportName = {
        Transaction: "Transaction",
        Settlement: "Settlement",
        Boarding: "Boarding",
        Returned: "Returned",
    } as const;
    export type ReportName = (typeof ReportName)[keyof typeof ReportName];
}
