/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The domain's owning entity's ID in Payabli. This value might be different than the `entityId`, depending on whether the domain is cascaded and whether it's inherited.`
 */
export type OwnerEntityId = number;
