// This file was auto-generated by Fern from our API Definition.

export interface PayabliCredentialsPascal {
    Service?: string;
    Mode?: number;
    MinTicket?: number;
    MaxTicket?: number;
    CfeeFix?: number;
    CfeeFloat?: number;
    CfeeMin?: number;
    CfeeMax?: number;
    AccountId?: string;
    ReferenceId?: number;
    acceptSameDayACH?: boolean;
    /** The default currency for the paypoint, either `USD` or `CAD`. */
    Currency?: string;
}
