/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface PayabliApiResponsePaymentLinks {
    isSuccess?: Payabli.IsSuccess;
    /** If `isSuccess` = true, this contains the payment link identifier. If `isSuccess` = false, this contains the reason of the error. */
    responseData?: string;
    responseText?: Payabli.ResponseText | undefined;
}
