/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

/**
 * The response for canceling a single payout transaction.
 */
export interface PayabliApiResponse0000 {
    isSuccess?: Payabli.IsSuccess;
    responseText: Payabli.ResponseText;
    pageIdentifier?: Payabli.PageIdentifier;
    responseCode?: Payabli.Responsecode;
    responseData?: PayabliApiResponse0000.ResponseData;
}

export namespace PayabliApiResponse0000 {
    export interface ResponseData {
        AuthCode?: Payabli.Authcode;
        avsResponseText?: Payabli.Avsresponsetext;
        CustomerId?: Payabli.Customeridtrans;
        cvvResponseText?: Payabli.Cvvresponsetext;
        methodReferenceId?: Payabli.MethodReferenceId;
        ReferenceId?: Payabli.Referenceidtrans;
        ResultCode?: Payabli.ResultCode;
        ResultText?: Payabli.Resulttext;
    }
}
