/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface PayabliApiResponse00 {
    isSuccess?: Payabli.IsSuccess;
    pageIdentifier?: Payabli.PageIdentifier;
    responseCode?: Payabli.Responsecode;
    responseData?: Payabli.Responsedata;
    responseText?: Payabli.ResponseText;
}
