// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface PayabliCredentialsPascal {
    /** The payment service that this credential applies to. A paypoint can support multiple services, each represented by its own credential object in the array. Possible values are `card` (credit/debit card), `ach` (ACH bank transfer), `check` (paper check), `vcard` (virtual card), `cloud` (card-present), `cash`, `managed` (managed payment service), and `wallet`. */
    Service?: string | undefined;
    /** The payment mode supported by this service. `0` for one-time payments, `1` for recurring payments, `2` for both. */
    Mode?: number | undefined;
    MinTicket?: Payabli.MinTicket | undefined;
    MaxTicket?: Payabli.MaxTicket | undefined;
    CfeeFix?: number | undefined;
    CfeeFloat?: number | undefined;
    CfeeMin?: number | undefined;
    CfeeMax?: number | undefined;
    AccountId?: string | undefined;
    ReferenceId?: number | undefined;
    acceptSameDayACH?: boolean | undefined;
    /** The default currency for the paypoint, either `USD` or `CAD`. */
    Currency?: string | undefined;
}
