/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface PayMethodCloud {
    device?: Payabli.Device | undefined;
    /** Method to use for the transaction. For cloud device transactions, the method is `cloud`. */
    method: "cloud";
    saveIfSuccess?: Payabli.SaveIfSuccess | undefined;
}
