/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

/**
 * Information about the payment method for the transaction.
 */
export type PaymentMethod =
    | Payabli.PayMethodCredit
    | {
          achAccount: Payabli.Achaccount;
          achAccountType?: Payabli.Achaccounttype | undefined;
          achCode?: Payabli.AchSecCode | undefined;
          achHolder: Payabli.AchHolder;
          achHolderType?: Payabli.AchHolderType | undefined;
          achRouting: Payabli.Achrouting;
          device?: Payabli.Device | undefined;
          method: "ach";
      }
    | Payabli.PayMethodStoredMethod
    | Payabli.PayMethodCloud
    | Payabli.Check
    | Payabli.Cash
    | Payabli.PayMethodBodyAllFields;
