/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

/**
 * Details about the payment.
 */
export interface PaymentDetail {
    /**
     * Array of payment categories/line items describing the amount to be paid
     * **Note**: These categories are for information only and are not validated against the total amount provided.
     */
    categories?: Payabli.PaymentCategories[];
    /** Object containing image of paper check. */
    checkImage?: Record<string, unknown>;
    /** A check number to be used in the ach transaction. **Required** for payment method = 'check'. */
    checkNumber?: string;
    /** Currency code ISO-4217. If not code is provided the currency in the paypoint setting is taken. Default is **USD**. */
    currency?: string;
    /** Service fee to be deducted from the total amount. This amount must be a number, percentages aren't accepted. If you are using a percentage-based fee schedule, you must calculate the value manually. */
    serviceFee?: number;
    /** Split funding instructions for the transaction. See [Split a Transaction](/developer-guides/money-in-split-funding) for more. */
    splitFunding?: Payabli.SplitFunding | undefined;
    /** Total amount to be charged. If a service fee is sent, then this amount should include the service fee." */
    totalAmount: number;
}
