/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

/**
 * Customer information. May be required, depending on the paypoint's settings. Required for subscriptions.
 */
export interface PayorData {
    additionalData?: Payabli.AdditionalData;
    billingAddress1?: Payabli.BillingAddressNullable | undefined;
    billingAddress2?: Payabli.BillingAddressAddtlNullable | undefined;
    billingCity?: Payabli.BillingCityNullable | undefined;
    billingCountry?: Payabli.BillingCountryNullable | undefined;
    billingEmail?: Payabli.Email | undefined;
    billingPhone?: Payabli.PhoneNumber;
    billingState?: Payabli.BillingStateNullable | undefined;
    /** Customer's billing ZIP code. For Pay In functions, this field supports 5-digit and 9-digit ZIP codes and alphanumeric Canadian postal codes. For example: "37615-1234" or "37615". */
    billingZip?: Payabli.BillingZipNullable | undefined;
    /** Customer's company name. */
    company?: string;
    customerId?: Payabli.CustomerId | undefined;
    customerNumber?: Payabli.CustomerNumberNullable | undefined;
    /** Customer/Payor first name. */
    firstName?: string;
    identifierFields?: Payabli.Identifierfields | undefined;
    /** Customer/Payor last name. */
    lastName?: string;
    shippingAddress1?: Payabli.Shippingaddress | undefined;
    shippingAddress2?: Payabli.Shippingaddressadditional | undefined;
    shippingCity?: Payabli.Shippingcity | undefined;
    shippingCountry?: Payabli.Shippingcountry | undefined;
    shippingState?: Payabli.Shippingstate | undefined;
    shippingZip?: Payabli.Shippingzip | undefined;
}
