// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface PayorFields {
    /** Flag indicating if the input field will show in container */
    display?: boolean | undefined;
    /** Flag indicating if the value in input field is read-only or not. */
    fixed?: boolean | undefined;
    /** Flag indicating if the input field is a customer identifier */
    identifier?: boolean | undefined;
    /** Label to display for field */
    label?: string | undefined;
    /** Name of field to show. Should be one of the standard customer fields or a custom field name */
    name?: string | undefined;
    order?: Payabli.Order | undefined;
    /** Flag indicating if the input field is required for validation */
    required?: boolean | undefined;
    /**
     * Type of validation to apply to the input field Accepted values:
     *
     *   - alpha for alphabetical
     *
     *   - numbers for numeric
     *
     *   - text for alphanumeric
     *
     *   - email for masked email address input
     *
     *   - phone for US phone numbers
     */
    validation?: string | undefined;
    /** Pre-populated value for field */
    value?: string | undefined;
    /**
     * Numeric value indicating the size of input relative to the container. Accepted values:
     *
     *     - 4 = 1/3
     *
     *     - 6 = 1/2
     *
     *     - 8 = 2/3
     *
     *     - 12 = 3/3
     */
    width?: number | undefined;
}
