/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

export interface PaypointData {
    address1?: Payabli.AddressNullable;
    address2?: Payabli.AddressAddtlNullable;
    bankData?: Payabli.BankData | undefined;
    boardingId?: Payabli.BoardingId;
    city?: Payabli.CityNullable;
    contacts?: Payabli.ContactsField | undefined;
    country?: Payabli.CountryNullable;
    credentials?: Payabli.PayabliCredentialsPascal[];
    dbaName?: Payabli.Dbaname;
    externalPaypointID?: Payabli.ExternalPaypointId;
    /** Fax number */
    fax?: Payabli.PhoneNumber;
    idPaypoint?: Payabli.Idpaypoint;
    legalName?: Payabli.Legalname;
    parentOrg?: Payabli.OrgData;
    paypointStatus?: Payabli.Paypointstatus;
    phone?: Payabli.PhoneNumber;
    serviceData?: Payabli.Services;
    state?: Payabli.StateNullable;
    summary?: Payabli.PaypointSummary;
    timeZone?: Payabli.Timezone;
    websiteAddress?: Payabli.Website;
    zip?: Payabli.Zip;
}
