// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface ProcessingSection {
    avgmonthly?: Payabli.TemplateElement | undefined;
    binperson?: Payabli.TemplateElement | undefined;
    binphone?: Payabli.TemplateElement | undefined;
    binweb?: Payabli.TemplateElement | undefined;
    bsummary?: Payabli.TemplateElement | undefined;
    highticketamt?: Payabli.TemplateElement | undefined;
    mcc?: Payabli.TemplateElement | undefined;
    subFooter?: Payabli.SubFooter | undefined;
    subHeader?: Payabli.SubHeader | undefined;
    ticketamt?: Payabli.TemplateElement | undefined;
    visible?: Payabli.Visible | undefined;
    whenCharged?: Payabli.TemplateElement | undefined;
    whenDelivered?: Payabli.TemplateElement | undefined;
    whenProvided?: Payabli.TemplateElement | undefined;
    whenRefunded?: Payabli.TemplateElement | undefined;
    CombinedBatches?: Payabli.TemplateElement | undefined;
    payoutAverageMonthlyVolume?: Payabli.TemplateElement | undefined;
    payoutHighTicketAmount?: Payabli.TemplateElement | undefined;
    payoutAverageTicketAmount?: Payabli.TemplateElement | undefined;
    payoutCreditLimit?: Payabli.TemplateElement | undefined;
}
