/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

export interface ProcessingSection {
    avgmonthly?: Payabli.TemplateElement;
    binperson?: Payabli.TemplateElement;
    binphone?: Payabli.TemplateElement;
    binweb?: Payabli.TemplateElement;
    bsummary?: Payabli.TemplateElement;
    highticketamt?: Payabli.TemplateElement;
    mcc?: Payabli.TemplateElement;
    subFooter?: Payabli.SubFooter;
    subHeader?: Payabli.SubHeader;
    ticketamt?: Payabli.TemplateElement;
    visible?: Payabli.Visible | undefined;
    whenCharged?: Payabli.TemplateElement;
    whenDelivered?: Payabli.TemplateElement;
    whenProvided?: Payabli.TemplateElement;
    whenRefunded?: Payabli.TemplateElement;
}
