// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface QueryResponseNotificationReportsRecordsItem {
    createdAt?: Payabli.CreatedAt | undefined;
    /** Unique identifier for the report. */
    id?: number | undefined;
    /** Indicator of whether the report can be downloaded. */
    isDownloadable?: boolean | undefined;
    /** Name of the report. */
    reportName?: string | undefined;
}
