// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 *
 */
export interface QueryBoardingLinksResponse {
    Records?: QueryBoardingLinksResponse.Records.Item[];
    Summary?: Payabli.QuerySummary;
}

export namespace QueryBoardingLinksResponse {
    export type Records = Records.Item[];

    export namespace Records {
        export interface Item {
            AcceptOauth?: Payabli.AcceptOauth | undefined;
            AcceptRegister?: Payabli.AcceptRegister | undefined;
            EntryAttributes?: Payabli.EntryAttributes;
            /** The record ID. */
            Id?: number;
            LastUpdated?: Payabli.LastModified | undefined;
            OrgParentName?: Payabli.OrgParentName;
            ReferenceName?: Payabli.ReferenceName;
            ReferenceTemplateId?: Payabli.ReferenceTemplateId;
            TemplateCode?: Payabli.TemplateCode | undefined;
            TemplateName?: Payabli.TemplateName;
        }
    }
}
