// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Response body for queries about chargebacks.
 */
export interface QueryChargebacksResponse {
    Records?: Payabli.QueryChargebacksResponseRecordsItem[] | undefined;
    Summary?: Payabli.QuerySummary | undefined;
}
