/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface QuerySummaryNoAmt {
    pageIdentifier?: Payabli.PageIdentifier;
    pageSize?: Payabli.Pagesize;
    totalPages?: Payabli.Totalrecords;
    totalRecords?: Payabli.Totalrecords;
}
