// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Response payload for queries related to transactions
 *
 * @example
 *     {
 *         Records: [{
 *                 ParentOrgName: "RealistRoofing",
 *                 PaypointDbaname: "Eagle-Pointe",
 *                 PaypointLegalname: "Eagle-Pointe",
 *                 PaypointEntryname: "entry399",
 *                 PaymentTransId: "399-8e7e5fc7-f483-43cc-9e78-d8a36ac857bf",
 *                 ConnectorName: "GP",
 *                 Method: "card",
 *                 PayorId: 155974,
 *                 PaymentData: {
 *                     MaskedAccount: "5XXXXXXXXXXX4415",
 *                     AccountExp: "12/29",
 *                     HolderName: "RENEE DESCARTES",
 *                     binData: {
 *                         binMatchedLength: "9",
 *                         binCardBrand: "MASTERCARD",
 *                         binCardType: "CREDIT",
 *                         binCardCategory: "MIXED PRODUCT",
 *                         binCardIssuer: "ALLIED IRISH BANKS, PLC",
 *                         binCardIssuerCountry: "IRELAND",
 *                         binCardIsRegulated: "False",
 *                         binCardUseCategory: "PERSONAL"
 *                     },
 *                     paymentDetails: {
 *                         totalAmount: 6.79,
 *                         serviceFee: 0,
 *                         currency: "USD"
 *                     }
 *                 },
 *                 TransStatus: -4,
 *                 PaypointId: 399,
 *                 splitFundingInstructions: [{}],
 *                 splitCount: 1,
 *                 TotalAmount: -6.79,
 *                 NetAmount: -6.79,
 *                 FeeAmount: 0,
 *                 SettlementStatus: 0,
 *                 Operation: "Reject",
 *                 Source: "api",
 *                 OrgId: 39,
 *                 TransactionTime: "2026-03-02T18:56:23.109188",
 *                 Customer: {
 *                     FirstName: "Blaise",
 *                     LastName: "Pascal",
 *                     CompanyName: "Pensees LLC",
 *                     BillingAddress1: "49912 Aufengrupt Pointe",
 *                     BillingAddress2: "apt 6",
 *                     BillingCity: "South Litzy",
 *                     BillingState: "FL",
 *                     BillingZip: "33000",
 *                     BillingCountry: "US",
 *                     BillingPhone: "+18955791994",
 *                     BillingEmail: "blaise.pascal@gmail.com",
 *                     CustomerNumber: "o99t",
 *                     customerId: 155974,
 *                     customerStatus: 1
 *                 },
 *                 TransactionEvents: [{
 *                         TransEvent: "Created",
 *                         EventData: "Card Reject - CTDR Id: 1379241",
 *                         EventTime: "2026-03-02T18:56:23.352035"
 *                     }]
 *             }],
 *         Summary: {
 *             totalRecords: 14,
 *             totalAmount: -79.48,
 *             totalNetAmount: -74.41,
 *             totalPages: 14,
 *             pageSize: 1
 *         }
 *     }
 */
export interface QueryResponseTransactions {
    Records?: Payabli.TransactionQueryRecords[] | undefined;
    Summary?: Payabli.QuerySummary | undefined;
}
