// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface QueryCFeeTransaction {
    cFeeTransid?: string | undefined;
    feeAmount?: number | undefined;
    operation?: string | undefined;
    refundId?: number | undefined;
    responseData?: Record<string, unknown> | undefined;
    settlementStatus?: number | undefined;
    transactionTime?: Payabli.TransactionTime | undefined;
    transStatus?: number | undefined;
}
