/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface QueryBoardingLinksResponseRecordsItem {
    AcceptOauth?: Payabli.AcceptOauth | undefined;
    AcceptRegister?: Payabli.AcceptRegister | undefined;
    EntryAttributes?: Payabli.EntryAttributes | undefined;
    /** The record ID. */
    Id?: number;
    LastUpdated?: Payabli.LastModified | undefined;
    OrgParentName?: Payabli.OrgParentName | undefined;
    ReferenceName?: Payabli.ReferenceName | undefined;
    ReferenceTemplateId?: Payabli.ReferenceTemplateId | undefined;
    TemplateCode?: Payabli.TemplateCode | undefined;
    TemplateName?: Payabli.TemplateName | undefined;
}
