// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface QueryTransactionPayorData {
    /** Array of field names to be used as identifiers. */
    Identifiers?: unknown[];
    /** Customer/Payor first name. */
    FirstName?: string;
    /** Customer/Payor last name. */
    LastName?: string;
    /** Customer's company name. */
    CompanyName?: string;
    /** Customer's billing address. */
    BillingAddress1?: string;
    /** Additional line for Customer's billing address. */
    BillingAddress2?: string;
    /** Customer's billing city. */
    BillingCity?: string;
    /** Customer's billing state. Must be 2-letter state code for address in US. */
    BillingState?: string;
    /** Customer's billing ZIP code. */
    BillingZip?: Payabli.BillingZip;
    /** Customer's billing country. */
    BillingCountry?: string;
    /** Customer's phone number. */
    BillingPhone?: string;
    /** Customer's email address. */
    BillingEmail?: Payabli.Email;
    CustomerNumber?: Payabli.CustomerNumberNullable;
    ShippingAddress1?: Payabli.Shippingaddress;
    ShippingAddress2?: Payabli.Shippingaddressadditional;
    ShippingCity?: Payabli.Shippingcity;
    ShippingState?: Payabli.Shippingstate;
    ShippingZip?: Payabli.Shippingzip;
    ShippingCountry?: Payabli.Shippingcountry;
    customerId?: Payabli.CustomerId;
    customerStatus?: Payabli.CustomerStatus;
    AdditionalData?: Payabli.AdditionalDataMap;
}
