/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface QueryResponseNotificationReportsRecordsItem {
    createdAt?: Payabli.CreatedAt;
    /** Unique identifier for the report. */
    id?: number;
    /** Indicator of whether the report can be downloaded. */
    isDownloadable?: boolean;
    /** Name of the report. */
    reportName?: string;
}
