// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Response for line item queries
 */
export interface QueryResponseItems {
    Records?: QueryResponseItems.Records.Item[];
    Summary?: Payabli.QuerySummary;
}

export namespace QueryResponseItems {
    export type Records = Records.Item[];

    export namespace Records {
        export interface Item {
            LineItem?: Payabli.LineItem;
            ParentOrgName?: Payabli.OrgParentName;
            /** The paypoint's DBA name. */
            PaypointDbaname?: Payabli.Dbaname;
            /** The paypoint's entry name (entrypoint). */
            PaypointEntryname?: Payabli.Entrypointfield;
            /** the Paypoint's legal name. */
            PaypointLegalname?: Payabli.Legalname;
        }
    }
}
