// This file was auto-generated by Fern from our API Definition.

/**
 * Remittance street address. Used for mailing paper checks. Required if any remittance address field is provided. Allowed characters are letters, numbers, spaces, and `. ,
 */
export type Remitaddress1 = string;
