// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * The required and recommended fields for a payment made with a stored payment method.
 */
export interface RequestSchedulePaymentMethodInitiator {
    initiator?: Payabli.Initiator | undefined;
    /** Payabli identifier of a tokenized payment method. */
    storedMethodId?: Payabli.Storedmethodid | undefined;
    storedMethodUsageType?: Payabli.StoredMethodUsageType | undefined;
}
