// This file was auto-generated by Fern from our API Definition.

/**
 * A note on a case.
 */
export interface RoomMessageView {
    /** The message's identifier. */
    id: number;
    /** The numeric id of the user who posted the note. */
    userId: number;
    /** The note text. */
    content: string;
    /** When the note was posted. */
    createdAt: string;
    /** When the note was last edited. Null when never edited. */
    updatedAt: string | null;
}
