/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface TemplateContentResponse {
    businessData?: Payabli.BusinessSection;
    documentsData?: Payabli.DocumentSection;
    ownershipData?: Payabli.OwnersSection;
    processingData?: Payabli.ProcessingSection;
    salesData?: Payabli.SalesSection;
    servicesData?: Payabli.ServicesSection;
    underwritingData?: Payabli.UnderwritingDataResponse;
}
