// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface Transfer {
    /** The transfer ID. */
    transferId: number;
    paypointId: Payabli.PaypointId;
    batchNumber: Payabli.BatchNumber;
    /** The currency of the batch, either USD or CAD. */
    batchCurrency: string | null;
    /** Number of records in the batch. */
    batchRecords: number | null;
    transferIdentifier: Payabli.TransferIdentifier;
    /** The ID of the batch the transfer belongs to. */
    batchId: number;
    /** The paypoint entryname. */
    paypointEntryName: string | null;
    /** The paypoint legal name. */
    paypointLegalName: Payabli.Legalname | null;
    /** The paypoint DBA name. */
    paypointDbaName: Payabli.Dbaname | null;
    /** The paypoint logo URL. */
    paypointLogo: string | null;
    /** The parent organization name. */
    parentOrgName: string | null;
    /** The parent organization ID. */
    parentOrgId: number | null;
    /** The parent organization entryname. */
    parentOrgEntryName: string | null;
    /** The parent organization logo URL. */
    parentOrgLogo: string | null;
    /** The external paypoint ID. */
    externalPaypointID: string | null;
    /** Bank account information for the transfer. */
    bankAccount: Payabli.TransferBankAccount | null;
    /** Date when the transfer occurred. */
    transferDate: string;
    /** The payment processor used for the transfer. */
    processor: string;
    /** The current status of the transfer. */
    transferStatus: number;
    /** Gross batch is the total amount of the payments grouped in the batch. This amount includes service fees. */
    grossAmount: number;
    /** Amount of chargebacks to be deducted from batch. */
    chargeBackAmount: number;
    /** Amount of ACH returns to be deducted from batch. */
    returnedAmount: number;
    /** Amount being held for fraud or risk concerns. */
    holdAmount: number;
    /** Amount of previously held funds that have been released after a risk review. */
    releasedAmount: number;
    /** Amount of charges and fees applied for services and transactions. */
    billingFeesAmount: number;
    /** Amount of payments captured in the batch cycle that are deposited separately. For example, checks or cash payments recorded in the batch but not deposited via Payabli, or card brands making a direct transfer in certain situations. */
    thirdPartyPaidAmount: number;
    /** Amount of corrections applied to Billing & Fees charges. */
    adjustmentsAmount: number;
    /** The net transfer amount after all deductions and additions. */
    netTransferAmount: number;
    /** The sum of each splitFundingAmount of each record in the transfer. */
    splitAmount: number | null;
    /** List of events associated with the transfer. */
    eventsData: Payabli.GeneralEvents[] | null;
    /** List of messages related to the transfer. */
    messages: Payabli.TransferMessage[] | null;
}
