/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index";

export interface TransferDetailRecord {
    /** Unique identifier for the transfer detail record */
    transferDetailId: number;
    /** The ID of the transfer this detail belongs to */
    transferId: number;
    /** The transaction ID in Payabli's system */
    transactionId: string;
    /** External transaction reference number */
    transactionNumber?: string;
    /** The ID of the paypoint this transaction belongs to */
    paypointId: number;
    /** The transaction type (credit or debit) */
    type: string;
    /** A field used to categorize the transaction details. Values include: auth, decline, refund, adj, cb, split */
    category?: string;
    /** The payment method used for the transaction */
    method: string;
    /** The gross amount of the transaction */
    grossAmount: number;
    /** Chargeback amount deducted from transaction */
    chargeBackAmount: number;
    /** ACH return amount deducted from transaction */
    returnedAmount: number;
    /** Refund amount deducted from transaction */
    refundAmount: number;
    /** Amount being held for fraud or risk concerns */
    holdAmount: number;
    /** Previously held funds that have been released after a risk review */
    releasedAmount: number;
    /** Charges applied for transactions and services */
    billingFeesAmount: number;
    /** Payments captured in the batch cycle that are deposited separately. For example,  checks or cash payments recorded in the batch but not deposited via Payabli,  or card brands making a direct transfer in certain situations. */
    thirdPartyPaidAmount: number;
    /** Corrections applied to Billing & Fees charges */
    adjustmentsAmount: number;
    /** The net amount after all deductions */
    netTransferAmount: number;
    /** Total amount directed to split funding destinations */
    splitFundingAmount: number;
    /** Detailed breakdown of billing fees applied to the transaction */
    billingFeesDetails?: Payabli.BillingFeeDetail[];
    /** The name of the parent organization */
    ParentOrgName?: Payabli.OrgParentName;
    /** The paypoint's DBA name */
    PaypointDbaname?: Payabli.Dbaname | undefined;
    /** The paypoint's legal name */
    PaypointLegalname?: Payabli.Legalname | undefined;
    /** The paypoint's entryname */
    PaypointEntryname?: string;
    /** The transaction ID for the payment */
    PaymentTransId?: string;
    /** The payment connector used to process the transaction */
    ConnectorName?: string;
    /** Processor information, used for troubleshooting and reporting. This field contains a value when the API key used to make the request has management permissions. */
    ExternalProcessorInformation?: string;
    /** Internal identifier used for processing */
    GatewayTransId?: string;
    /** Custom identifier for the transaction */
    OrderId?: Payabli.Orderid | undefined;
    /** Payment method used: card, ach, or wallet */
    Method?: string;
    /** The batch number the transaction was included in */
    BatchNumber?: Payabli.Batchnumber | undefined;
    /** The amount of the batch */
    BatchAmount?: number;
    /** Unique ID for customer linked to the transaction */
    PayorId?: number;
    /** Details about the payment method and transaction */
    PaymentData?: Payabli.QueryPaymentData;
    /** Status of transaction. See [the docs](/references/money-in-statuses#money-in-transaction-status) for a full reference. */
    TransStatus?: number;
    /** Transaction total amount (including service fee or sub-charge) */
    TotalAmount?: number;
    /** Net amount paid */
    NetAmount?: Payabli.Netamountnullable | undefined;
    /** Service fee or sub-charge applied */
    FeeAmount?: number;
    /** Settlement status for transaction. See [the docs](/references/money-in-statuses#payment-funding-status) for a full reference. */
    SettlementStatus?: number;
    /** The transaction's operation */
    Operation?: string;
    /** Details about the transaction response */
    ResponseData?: Payabli.QueryResponseData;
    /** Custom identifier to indicate the transaction or request source */
    Source?: Payabli.Source | undefined;
    /** Reference to the subscription or schedule that originated the transaction */
    ScheduleReference?: number;
    /** ID of immediate parent organization */
    OrgId?: Payabli.Orgid | undefined;
    /** Identifier of refund transaction linked to this payment */
    RefundId?: number;
    /** Identifier of return/chargeback transaction linked to this payment */
    ReturnedId?: number;
    /** Identifier of chargeback transaction */
    ChargebackId?: number;
    /** Identifier of retrieval request */
    RetrievalId?: number;
    /** Additional transaction data */
    TransAdditionalData?: unknown;
    /** Associated invoice data */
    invoiceData?: Payabli.BillData;
    /** Internal reference ID to the payment page capturing the payment */
    EntrypageId?: number;
    /** A custom identifier for the paypoint */
    externalPaypointID?: Payabli.ExternalPaypointId | undefined;
    /** Transaction date and time, in UTC */
    TransactionTime?: Payabli.Datetimenullable | undefined;
    /** Customer information associated with the transaction */
    Customer?: Payabli.QueryTransactionPayorData;
    /** Split funding instructions for the transaction */
    splitFundingInstructions?: Payabli.SplitFunding | undefined;
    /** Service Fee or sub-charge transactions associated to the main transaction */
    CfeeTransactions?: Payabli.QueryCFeeTransaction[];
    /** Events associated with this transaction */
    TransactionEvents?: Payabli.QueryTransactionEvents[];
    /** Pending fee amount for the transaction */
    PendingFeeAmount?: Payabli.PendingFeeAmount | undefined;
    /** Indicates if the transaction was flagged for risk */
    RiskFlagged?: boolean;
    /** Timestamp when the transaction was flagged for risk */
    RiskFlaggedOn?: string;
    /** Current risk status of the transaction */
    RiskStatus?: string;
    /** Reason for risk flagging */
    RiskReason?: string;
    /** Action taken due to risk assessment */
    RiskAction?: string;
    /** Numeric code representing the risk action */
    RiskActionCode?: number;
    /** Identifier of registered cloud device used in the transaction */
    DeviceId?: Payabli.Device | undefined;
    /** Standard Entry Class (SEC) code for ACH transactions */
    AchSecCode?: Payabli.AchSecCode;
    /** Type of ACH account holder (personal or business) */
    AchHolderType?: Payabli.AchHolderType;
    /** IP address of the transaction source */
    IPAddress?: string;
}
