/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

export interface TransferBankAccount {
    accountNumber: Payabli.AccountNumber;
    routingNumber: Payabli.RoutingAccount;
}
