/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../index.js";

export interface TransactionOutQueryRecord {
    /** Identifier of payout transaction. */
    IdOut?: number;
    CreatedAt?: Payabli.CreatedAt;
    /** Any comment or description for payout transaction. */
    Comments?: Payabli.Comments;
    /** Vendor related to the payout transaction. */
    Vendor?: Payabli.VendorQueryRecord;
    PaypointDbaname?: Payabli.Dbaname;
    PaypointLegalname?: Payabli.Legalname;
    /** Internal status of transaction. */
    Status?: number;
    /** Timestamp when payment record was updated, in UTC. */
    LastUpdated?: Payabli.LastModified | undefined;
    /** Transaction total amount (including service fee or sub-charge). */
    TotalAmount?: number;
    NetAmount?: Payabli.Netamountnullable | undefined;
    FeeAmount?: Payabli.FeeAmount;
    Source?: Payabli.Source;
    ParentOrgName?: Payabli.OrgParentName;
    ParentOrgId?: Payabli.Orgid;
    /** The batch number for the payout transaction. */
    BatchNumber?: string;
    /** Status of payout transaction. */
    PaymentStatus?: string;
    /** Method of payment applied to the transaction. */
    PaymentMethod?: string;
    CardToken?: string;
    /** Paper check number related to payout transaction. */
    CheckNumber?: string;
    /** Object referencing to paper check image. */
    CheckData?: Payabli.FileContent;
    PaymentId?: Payabli.PaymentIdString;
    PaymentData?: Payabli.QueryPaymentData;
    /** Events associated to this transaction. */
    Bills?: Payabli.BillPayOutData[];
    /** Events associated to this transaction. */
    Events?: Payabli.QueryTransactionEvents[];
    externalPaypointID?: Payabli.ExternalPaypointId;
    EntryName?: Payabli.Entrypointfield;
    Gateway?: Payabli.Gatewayfield;
    /** ID of the batch the transaction belongs to. */
    BatchId?: string;
    HasVcardTransactions?: Payabli.HasVcardTransactions | undefined;
    IsSameDayACH?: Payabli.IsSameDayAch | undefined;
    ScheduleId?: Payabli.ScheduleId;
    SettlementStatus?: Payabli.SettlementStatusPayout;
    RiskFlagged?: Payabli.RiskFlagged | undefined;
    RiskFlaggedOn?: Payabli.RiskFlaggedOn | undefined;
    RiskStatus?: Payabli.RiskStatus;
    RiskReason?: Payabli.RiskReason;
    RiskAction?: Payabli.RiskAction;
    RiskActionCode?: Payabli.RiskActionCode | undefined;
    PayoutProgram?: Payabli.PayoutProgram;
}
