// This file was auto-generated by Fern from our API Definition.

/**
 * Status of transaction. See [the docs](/developers/references/money-in-statuses#money-in-transaction-status) for a full reference.
 */
export type TransStatus = number;
