// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface TransactionOutQueryRecord {
    /** Identifier of payout transaction. */
    IdOut?: number | undefined;
    CreatedAt?: Payabli.CreatedAt | undefined;
    /** Any comment or description for payout transaction. */
    Comments?: Payabli.Comments | undefined;
    /** Vendor related to the payout transaction. */
    Vendor?: Payabli.VendorQueryRecord | undefined;
    PaypointDbaname?: Payabli.Dbaname | undefined;
    PaypointLegalname?: Payabli.Legalname | undefined;
    /** Internal status of transaction. */
    Status?: number | undefined;
    /** Timestamp when payment record was updated, in UTC. */
    LastUpdated?: Payabli.LastModified | undefined;
    /** Transaction total amount (including service fee or sub-charge). */
    TotalAmount?: number | undefined;
    NetAmount?: Payabli.Netamountnullable | undefined;
    FeeAmount?: Payabli.FeeAmount | undefined;
    Source?: Payabli.Source | undefined;
    ParentOrgName?: Payabli.OrgParentName | undefined;
    ParentOrgId?: Payabli.Orgid | undefined;
    /** The batch number for the payout transaction. */
    BatchNumber?: string | undefined;
    /** Status of payout transaction. */
    PaymentStatus?: string | undefined;
    /** Method of payment applied to the transaction. */
    PaymentMethod?: string | undefined;
    CardToken?: string | undefined;
    /** Paper check number related to payout transaction. */
    CheckNumber?: string | undefined;
    /** Object referencing to paper check image. */
    CheckData?: Payabli.FileContent | undefined;
    PaymentId?: Payabli.PaymentIdString | undefined;
    PaymentData?: Payabli.QueryPaymentData | undefined;
    /** Events associated to this transaction. */
    Bills?: Payabli.BillPayOutData[] | undefined;
    /** Events associated to this transaction. */
    Events?: Payabli.QueryTransactionEvents[] | undefined;
    externalPaypointID?: Payabli.ExternalPaypointId | undefined;
    EntryName?: Payabli.Entrypointfield | undefined;
    Gateway?: Payabli.Gatewayfield | undefined;
    /** ID of the batch the transaction belongs to. */
    BatchId?: string | undefined;
    HasVcardTransactions?: Payabli.HasVcardTransactions | undefined;
    IsSameDayACH?: Payabli.IsSameDayAch | undefined;
    ScheduleId?: Payabli.ScheduleId | undefined;
    SettlementStatus?: Payabli.SettlementStatusPayout | undefined;
    RiskFlagged?: Payabli.RiskFlagged | undefined;
    RiskFlaggedOn?: Payabli.RiskFlaggedOn | undefined;
    RiskStatus?: Payabli.RiskStatus | undefined;
    RiskReason?: Payabli.RiskReason | undefined;
    RiskAction?: Payabli.RiskAction | undefined;
    RiskActionCode?: Payabli.RiskActionCode | undefined;
    PayoutProgram?: Payabli.PayoutProgram | undefined;
}
