// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

/**
 * Response wrapper for declined v2 Money In transaction endpoints (HTTP 402). Returned when a transaction is declined by the card network or issuer. All decline responses use this format with unified response codes starting with 'D'. The `data` field contains transaction details.
 */
export interface V2DeclinedTransactionResponseWrapper {
    code: Payabli.V2ResponseCode;
    reason: Payabli.V2ResponseReason;
    explanation: Payabli.V2ResponseExplanation;
    action: Payabli.V2ResponseAction;
    data: Payabli.V2TransactionDetails;
    /** Pagination token (equivalent to `pageIdentifier` in v1 APIs). Returns `null` when pagination is not applicable. */
    token: string | null;
}
