// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../index.js";

export interface VCardSummary {
    totalPages: Payabli.Totalpages;
    totalRecords: Payabli.Totalrecords;
    /** Total amount for the records. */
    totalAmount: number;
    /** Total number of active vCards. */
    totalactive: number;
    /** Total amount of active vCards. */
    totalamounteactive: number;
    /** Total balance of active vCards. */
    totalbalanceactive: number;
    pageIdentifier?: Payabli.PageIdentifier;
    pageSize?: Payabli.Pagesize;
}
