// This file was auto-generated by Fern from our API Definition.

/**
 * The vendor's preferred payment method. Can be one of:
 * - `"managed"` - Managed payment method
 * - `"vcard"` - Virtual card payment method
 * - `"check"` - Check payment method
 * - `"ach"` - ACH payment method
 */
export type VendorPaymentMethodString = string;
