// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ActiveBills: 2,
 *         PendingBills: 4,
 *         InTransitBills: 3,
 *         PaidBills: 18,
 *         OverdueBills: 1,
 *         ApprovedBills: 5,
 *         DisapprovedBills: 1,
 *         TotalBills: 34,
 *         ActiveBillsAmount: 1250.75,
 *         PendingBillsAmount: 2890.5,
 *         InTransitBillsAmount: 1675.25,
 *         PaidBillsAmount: 15420.8,
 *         OverdueBillsAmount: 425,
 *         ApprovedBillsAmount: 3240.9,
 *         DisapprovedBillsAmount: 180,
 *         TotalBillsAmount: 25083.2
 *     }
 */
export interface VendorSummary {
    ActiveBills?: number;
    PendingBills?: number;
    InTransitBills?: number;
    PaidBills?: number;
    OverdueBills?: number;
    ApprovedBills?: number;
    DisapprovedBills?: number;
    TotalBills?: number;
    ActiveBillsAmount?: number;
    PendingBillsAmount?: number;
    InTransitBillsAmount?: number;
    PaidBillsAmount?: number;
    OverdueBillsAmount?: number;
    ApprovedBillsAmount?: number;
    DisapprovedBillsAmount?: number;
    TotalBillsAmount?: number;
}
