// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             customerData: {
 *                 firstName: "Tamara",
 *                 lastName: "Bagratoni",
 *                 customerNumber: "3"
 *             },
 *             invoiceData: {
 *                 items: [{
 *                         itemProductName: "Adventure Consult",
 *                         itemDescription: "Consultation for Georgian tours",
 *                         itemCost: 100,
 *                         itemQty: 1,
 *                         itemMode: 1,
 *                         itemTotalAmount: 1
 *                     }, {
 *                         itemProductName: "Deposit ",
 *                         itemDescription: "Deposit for trip planning",
 *                         itemCost: 882.37,
 *                         itemQty: 1,
 *                         itemTotalAmount: 1
 *                     }],
 *                 invoiceDate: "2025-10-19",
 *                 invoiceType: 0,
 *                 invoiceStatus: 1,
 *                 frequency: "onetime",
 *                 invoiceAmount: 982.37,
 *                 discount: 10,
 *                 invoiceNumber: "INV-3"
 *             }
 *         }
 *     }
 */
export interface AddInvoiceRequest {
    forceCustomerCreation?: Payabli.ForceCustomerCreation | undefined;
    idempotencyKey?: Payabli.IdempotencyKey;
    body: Payabli.InvoiceDataRequest;
}
