/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../../index";

/**
 * @example
 *     {
 *         applePay: {
 *             isEnabled: false
 *         },
 *         googlePay: {
 *             isEnabled: false
 *         }
 *     }
 */
export interface UpdatePaymentMethodDomainRequest {
    applePay?: Payabli.UpdatePaymentMethodDomainRequestWallet;
    googlePay?: Payabli.UpdatePaymentMethodDomainRequestWallet;
}
