// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

export type AddNotificationRequest =
    /**
     * Create a standard webhook, email, or SMS notification. */
    | Payabli.NotificationStandardRequest
    /**
     * Create an auto-generated report. */
    | Payabli.NotificationReportRequest;
