/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../../index";

/**
 * @example
 *     {
 *         contacts: [{
 *                 contactEmail: "herman@hermanscoatings.com",
 *                 contactName: "Herman Martinez",
 *                 contactPhone: "3055550000",
 *                 contactTitle: "Owner"
 *             }],
 *         orgAddress: "123 Walnut Street",
 *         orgCity: "Johnson City",
 *         orgCountry: "US",
 *         orgEntryName: "pilgrim-planner",
 *         orgId: "123",
 *         orgName: "Pilgrim Planner",
 *         orgState: "TN",
 *         orgTimezone: -5,
 *         orgType: 0,
 *         orgWebsite: "www.pilgrimageplanner.com",
 *         orgZip: "37615"
 *     }
 */
export interface OrganizationData {
    services?: Payabli.ServiceCost[];
    billingInfo?: Payabli.Instrument;
    contacts?: Payabli.ContactsField | undefined;
    hasBilling?: boolean;
    hasResidual?: boolean;
    orgAddress?: Payabli.Orgaddress | undefined;
    orgCity?: Payabli.Orgcity | undefined;
    orgCountry?: Payabli.Orgcountry | undefined;
    orgEntryName?: Payabli.Orgentryname | undefined;
    orgId?: Payabli.Orgidstring | undefined;
    orgLogo?: Payabli.FileContent;
    orgName?: Payabli.Orgname;
    orgParentId?: Payabli.Orgparentid;
    orgState?: Payabli.Orgstate | undefined;
    orgTimezone?: Payabli.Orgtimezone | undefined;
    orgType?: Payabli.Orgtype;
    orgWebsite?: Payabli.Orgwebsite | undefined;
    orgZip?: Payabli.Orgzip | undefined;
    replyToEmail?: Payabli.ReplyToEmail;
}
