// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

export interface AddUserResponse {
    isSuccess?: Payabli.IsSuccess | undefined;
    /** The response data. */
    responseData?: string | undefined;
    responseText: Payabli.ResponseText;
}
