/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../index";

export interface AddUserResponse {
    isSuccess?: Payabli.IsSuccess;
    /** The response data. */
    responseData?: string;
    responseText?: Payabli.ResponseText;
}
