// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

/**
 * Configuration for payment method selection on Pay Out payment links.
 */
export interface MethodElementOut {
    /** Flag indicating if all allowed payment methods will be pre-selected. */
    allMethodsChecked?: boolean | undefined;
    /** When `true`, the vendor can select from multiple payment methods. When `false`, only the default method is shown. */
    allowMultipleMethods?: boolean | undefined;
    /** The default payment method to highlight on the payment link page. For example, `"vcard"`, `"ach"`, or `"check"`. */
    defaultMethod?: string | undefined;
    /** When `true`, the payment methods section is displayed on the payment link page. */
    enabled?: boolean | undefined;
    /** Header text for the payment methods section. */
    header?: string | undefined;
    methods?: Payabli.MethodsListOut | undefined;
    /** Display order of the payment methods section on the page. */
    order?: number | undefined;
    /** When `true`, a preview of the virtual card is shown on the payment link page. */
    showPreviewVirtualCard?: boolean | undefined;
}
