// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

/**
 * Response for creating a ghost card.
 */
export interface CreateGhostCardResponse {
    isSuccess?: Payabli.IsSuccess | undefined;
    responseText: Payabli.ResponseText;
    responseData?: CreateGhostCardResponse.ResponseData | undefined;
}

export namespace CreateGhostCardResponse {
    export interface ResponseData {
        /** Card token for the ghost card. Use this value to reference the card in subsequent operations (update, cancel, etc.). */
        ReferenceId?: string | undefined;
        ResultCode?: Payabli.ResultCode | undefined;
        ResultText?: Payabli.Resulttext | undefined;
    }
}
