// This file was auto-generated by Fern from our API Definition.

import type * as Payabli from "../../../index.js";

export interface PaypointMoveRequest {
    entryPoint: Payabli.Entrypointfield;
    /** The ID for the paypoint's new parent organization. */
    newParentOrganizationId: number;
    /** Optional notification request object for a webhook */
    notificationRequest?: Payabli.NotificationRequest | undefined;
}
