// This file was auto-generated by Fern from our API Definition.

export const GetProfileBillingRequestEntityType = {
    Organization: "Organization",
    Paypoint: "Paypoint",
    Template: "Template",
    Application: "Application",
} as const;
export type GetProfileBillingRequestEntityType =
    (typeof GetProfileBillingRequestEntityType)[keyof typeof GetProfileBillingRequestEntityType];
