/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../index";

/**
 * Information about the payment method for the transaction.
 */
export type RequestTokenStoragePaymentMethod = Payabli.TokenizeCard | Payabli.TokenizeAch | Payabli.ConvertToken;
