// This file was auto-generated by Fern from our API Definition.

export interface OcrBillItem {
    itemTotalAmount?: number | undefined;
    itemTaxAmount?: number | undefined;
    itemTaxRate?: number | undefined;
    itemProductCode?: string | undefined;
    itemProductName?: string | undefined;
    itemDescription?: string | undefined;
    itemCommodityCode?: string | undefined;
    itemUnitOfMeasure?: string | undefined;
    itemCost?: number | undefined;
    itemQty?: number | undefined;
    itemMode?: number | undefined;
    itemCategories?: string[] | undefined;
}
