/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Payabli from "../../../index.js";

export interface PayabliApiResponseOcr {
    isSuccess: Payabli.IsSuccess;
    responseText: Payabli.ResponseText;
    responseCode: Payabli.Responsecode;
    /** Details of the OCR processing result */
    responseData?: Payabli.OcrResponseData;
}
